export { incomeTaxCalc } from './incomeTax';
export { bituachLeumiCalc } from './bituachLeumi';
export { incomeTaxBandsCalc } from './incomeTaxBands';
export { nationalInsuranceSelfEmp } from './nationalInsuranceSelfEmp';
export { pensionContributionCalc } from './pensionContribution';
export { pensionMinCalc } from './pensionLegalMin';
export { pensionReliefCalc } from './pensionReliefEmployee';
export { pensionReliefCalc as pensionReliefCalcSelfEmp } from './pensionReliefSelfEmp';
export { studyFundCalc } from './studyFund';
export { studyFundAllowances } from './studyFundAllowances';
